name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_API_PORT: ${{ secret.REACT_APP_API_PORT}}
        REACT_APP_API_URL: ${{ secret.REACT_APP_API_URL }}
        REACT_APP_BASENAME: ${{ secret.REACT_APP_BASENAME }} 
        REACT_APP_DICTIONARY_KEY: ${{ REACT_APP_DICTIONARY_KEY }}
        REACT_APP_NODE_ENV:  ${{ secret.REACT_APP_NODE_ENV }} 
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
